#! /usr/bin/env bash

DATE=$(date +%Y_%m_%d)
INPUT=$@

# first, strip underscores
CLEAN=${INPUT//_/}
# next, replace spaces with underscores
CLEAN=${CLEAN// /_}
# now, clean out anything that's not alphanumeric or an underscore
CLEAN=${CLEAN//[^a-zA-Z0-9_]/}
# finally, lowercase with TR
CLEAN=`echo -n $CLEAN | tr A-Z a-z`

TITLE=$CLEAN

FILENAME=${DATE}_$TITLE.md

nvim $FILENAME
