#!/usr/bin/env bash

set -e

profile_name=$1

if [ -f ~/.screenlayout/monitor.sh ]; then rm -f ~/.screenlayout/monitor.sh; fi
ln -s ~/.screenlayout/$profile_name.sh ~/.screenlayout/monitor.sh
~/.screenlayout/monitor.sh
