#!/usr/bin/env bash

set -e

cd $NOTES_DIR
wmctrl -a WIKI_WINDOW || kitty -T "WIKI_WINDOW" --override font_family=ProFontIIxNerdFontMono --override font_size=12.0 nvim +ZenMode "+set bg=light" wiki/readme.md &
