#!/usr/bin/env bash
#
# Copyright (C) 2021 Andreas Lindlbauer
# Licensed under the terms of EUPLv1.2.
#
# i3blocks blocklet script to monitor the (nord)vpn connection

vpnstatus="📢"
nordvpn_output=$(nordvpn status | cat -v | sed -e 's/\^M-^M  ^M//g' )

if [[ "${nordvpn_output}" =~ "Status: Connected" ]]; then
    server=$(nordvpn status | grep Server | awk -F' ' '{print $2" "$3}')
    vpnstatus="🥸 $server"
fi

if [[ "${nordvpn_output}" =~ "A new version of NordVPN is available!" ]]; then
    vpnstatus="$vpnstatus [🡅]"
fi

if [ "${nordvpn_output}" = "Status: Disconnected" ]; then
    vpnstatus="📢"
elif [[ "$nordvpn_output" == *\/* ]] || [[ "$nordvpn_output" == *\\* ]]; then
    vpnstatus="Something's very wrong"
fi

echo "$vpnstatus"
